# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='project',
            name='long_description',
            field=models.TextField(default='No long description provided'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(default='No short description provided', max_length=255),
        ),
    ]
