# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160506_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(default='No short description provided'),
        ),
    ]
